import { useState, useSyncExternalStore, type ReactNode } from 'react'
import Link from 'next/link'
import Icon, { type IconName } from '../Icon'
import { Avatar, Logo, Verified } from '../Identity'
import { people, trends } from '@/features/feed/data/feed-content'
import type { Profile } from '@/shared/types/post'

const navigation: { id: string; label: string; icon: IconName }[] = [
  { id: 'home', label: 'Trang chủ', icon: 'home' },
  { id: 'search', label: 'Khám phá', icon: 'search' },
  { id: 'bell', label: 'Thông báo', icon: 'bell' },
  { id: 'mail', label: 'Tin nhắn', icon: 'mail' },
  { id: 'bookmark', label: 'Đã lưu', icon: 'bookmark' },
  { id: 'user', label: 'Hồ sơ', icon: 'user' },
]

function subscribeTheme(callback: () => void) {
  window.addEventListener('postr-theme-change', callback)
  return () => window.removeEventListener('postr-theme-change', callback)
}

export default function SiteLayout({ route, profile, following, unread, onFollow, onSearch, onCompose, children }: {
  route: string; profile: Profile; following: string[]; unread: boolean
  onFollow: (handle: string) => void; onSearch: () => void; onCompose: () => void; children: ReactNode
}) {
  const [search, setSearch] = useState('')
  const theme = useSyncExternalStore(subscribeTheme, () => document.documentElement.dataset.theme ?? 'dark', () => 'dark')

  function toggleTheme() {
    const next = theme === 'dark' ? 'light' : 'dark'
    document.documentElement.dataset.theme = next
    document.querySelector<HTMLMetaElement>('meta[name="theme-color"]')!.content = next === 'dark' ? '#171614' : '#f5f0e8'
    try { localStorage.setItem('postr-theme', next) } catch { /* Theme still works for this session. */ }
    window.dispatchEvent(new Event('postr-theme-change'))
  }

  const active = navigation.find(item => item.id === route) ?? navigation[0]
  return <>
    <Link href="/admin" className="fixed right-4 bottom-24 z-20 flex min-h-11 items-center rounded-full border border-edge bg-card px-4 text-xs font-bold shadow-sm min-[601px]:hidden">Admin demo</Link>
    <a href="#main-content" className="skip-link fixed left-[16px] top-[-80px] z-[30] p-[15px] bg-card [border:2px_solid_var(--color-edge)] [&:focus]:top-[16px]" onClick={event => { event.preventDefault(); document.getElementById('main-content')?.focus() }}>Đến nội dung chính</a>
    <div className="shell grid grid-cols-[220px_minmax(0,_600px)_310px] gap-[28px] [width:min(1186px,_calc(100%_-_48px))] [margin:0_auto] max-[1130px]:grid-cols-[74px_minmax(0,_600px)_280px] max-[1130px]:[width:calc(100%_-_40px)] max-[1130px]:gap-[22px] max-[880px]:grid-cols-[74px_minmax(0,_620px)] max-[880px]:[width:min(730px,_100%)] max-[880px]:gap-[16px] max-[600px]:block max-[600px]:w-full">
      <aside className="rail sticky top-0 h-dvh [padding:32px_6px_24px_0] flex flex-col overflow-y-auto [scrollbar-width:none]! [&::-webkit-scrollbar]:hidden max-[1130px]:items-center max-[1130px]:[&_.brand]:ml-0 max-[1130px]:[&_.brand_>_span:last-child]:hidden max-[600px]:hidden" aria-label="Điều hướng chính">
        <Logo /><p className="rail-caption [margin:16px_0_30px_12px] text-[8px] tracking-[1.1px] text-muted max-[1130px]:hidden">MỖI GÓC NHÌN, MỘT CÂU CHUYỆN.</p>
        <nav className="nav grid gap-[7px] max-[1130px]:mt-[35px]">{navigation.map(item => <a className={`nav-link relative flex items-center gap-[15px] min-h-[51px] [padding:12px_16px] [border:1.5px_solid_transparent] rounded-[100px] text-[15px] font-bold [transition:background_.15s] [&:hover]:bg-[light-dark(#fffdf880,_#ffffff09)] [&.active]:border-edge [&.active]:bg-card [&.active]:shadow-[3px_3px_0_light-dark(#e8dfd1,_#0c0b0a)] [&.active::after]:w-[7px] [&.active::after]:h-[7px] [&.active::after]:ml-auto [&.active::after]:rounded-full [&.active::after]:bg-accent [&.active::after]:content-[''] max-[1130px]:[&_>_span:last-child]:hidden max-[1130px]:justify-center max-[1130px]:w-[50px] max-[1130px]:h-[50px] max-[1130px]:p-0 max-[1130px]:[&.active::after]:absolute max-[1130px]:[&.active::after]:right-[5px] max-[1130px]:[&.active::after]:bottom-[8px] max-[1130px]:[&.active::after]:w-[5px] max-[1130px]:[&.active::after]:h-[5px] ${active.id === item.id ? 'active' : ''}`} href={`#${item.id}`} key={item.id} aria-label={item.label} aria-current={active.id === item.id ? 'page' : undefined}><span className="nav-icon relative flex"><Icon name={item.icon} />{item.id === 'bell' && unread && <i className="notification-dot absolute top-0 right-[-1px] h-[7px] w-[7px] bg-accent [border:1px_solid_var(--color-paper)] rounded-full" />}</span><span>{item.label}</span></a>)}</nav>
        <button className="[font-family:inherit] primary flex items-center justify-center gap-[12px] w-full min-h-[49px] mt-[27px] [padding:12px_20px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-ink text-card shadow-[4px_4px_0_var(--color-accent)] font-bold [&:hover]:bg-[light-dark(#444039,_#d7cbbb)] max-[1130px]:[&_>_span]:hidden max-[1130px]:w-[50px] max-[1130px]:h-[50px] max-[1130px]:p-0" aria-label="Đăng bài" onClick={onCompose}><Icon name="pen" /><span>Đăng bài</span></button>
        <Link href="/admin" className="mt-5 flex min-h-11 items-center justify-center rounded-full border border-line px-3 text-xs font-bold text-muted hover:bg-card">Admin demo</Link>
        <div className="rail-note flex items-center gap-[8px] [margin:26px_9px] text-[10px] text-muted max-[1130px]:hidden"><span className="live-dot inline-block shrink-0 w-[6px] h-[6px] rounded-full bg-green" /> Một chút kết nối mỗi ngày.</div>
        <a className="profile-mini flex items-center gap-[10px] mt-auto p-[12px] [border:1px_solid_var(--color-line)] rounded-[16px] bg-[light-dark(#fffdf87a,_#211f1c99)] text-[13px] [&_>_div]:overflow-hidden [&_>_div]:text-ellipsis [&_strong]:whitespace-nowrap [&_small]:text-muted [&_small]:text-[11px] [&_>_svg]:w-[16px] [&_>_svg]:ml-auto [&_>_svg]:[transform:rotate(180deg)] max-[1130px]:[&_>_div]:hidden max-[1130px]:[&_>_svg]:hidden max-[1130px]:p-[4px] max-[1130px]:[border:0] max-[1130px]:bg-transparent" href="#user" aria-label="Hồ sơ của bạn"><Avatar person={profile} /><div><strong>{profile.name}</strong><br /><small className="text-xs">{profile.handle}</small></div><Icon name="arrow" /></a>
      </aside>
      <main className="main-surface min-w-0 min-h-dvh [border-inline:1px_solid_var(--color-line)] bg-[light-dark(#fffdf8b8,_#1d1b18d9)] [&:has(.conversation)]:flex [&:has(.conversation)]:flex-col [&:has(.conversation)]:h-dvh [&:has(.conversation)_.topbar]:shrink-0 max-[600px]:min-h-dvh max-[600px]:[border:0] max-[600px]:pb-[85px]" id="main-content" tabIndex={-1}>
        <header className="topbar sticky z-[5] top-0 [border-bottom:1px_solid_var(--color-line)] bg-[light-dark(#f9f5edf0,_#1b1917f0)] [backdrop-filter:blur(16px)]"><div className="mobile-brand hidden max-[600px]:flex max-[600px]:items-center max-[600px]:justify-between max-[600px]:[padding:8px_16px_0] max-[600px]:[&_.brand]:m-0 max-[600px]:[&_.brand]:text-[28px] max-[600px]:[&_.brand-mark]:w-[30px] max-[600px]:[&_.brand-mark]:h-[30px] max-[600px]:[&_.brand-mark]:text-[18px] max-[600px]:[&_.avatar]:w-[32px] max-[600px]:[&_.avatar]:h-[32px] max-[600px]:[&_.avatar]:text-[16px]"><Logo /><div className="mobile-header-actions max-[600px]:flex max-[600px]:items-center max-[600px]:gap-[8px] max-[600px]:[&_>_a]:grid max-[600px]:[&_>_a]:place-items-center max-[600px]:[&_>_a]:w-[44px] max-[600px]:[&_>_a]:h-[44px]"><button className="[font-family:inherit] icon-button inline-grid place-items-center [border:0] bg-transparent rounded-full shrink-0 w-[44px] h-[44px] text-blue [&:hover]:bg-[light-dark(#2466c20d,_#86b6f612)]   compose-trigger max-[600px]:[&.compose-trigger]:[border:1px_solid_var(--color-edge)] max-[600px]:[&.compose-trigger]:bg-accent max-[600px]:[&.compose-trigger]:text-[#24221f] max-[600px]:[&:hover]:bg-[#ff906a]" aria-label="Đăng bài" onClick={onCompose}><Icon name="pen" /></button><a href="#user" aria-label="Hồ sơ của bạn"><Avatar person={profile} /></a></div></div><div className="page-heading flex items-center justify-between gap-[16px] min-h-[88px] [padding:20px_24px] [&_small]:text-[8px] [&_small]:text-muted [&_small]:tracking-[1.8px] [&_h1]:[margin:5px_0_0] [&_h1]:text-[23px] [&_h1]:font-serif [&_h1]:tracking-[-.8px] max-[600px]:min-h-[43px] max-[600px]:[padding:3px_18px_12px] max-[600px]:[&_small]:hidden max-[600px]:[&_h1]:text-[21px]"><div><small className="text-xs">KHÔNG GIAN CỦA BẠN</small><h1 className="[margin:.67em_0] font-bold">{route === 'post' ? 'Bài đăng' : active.label}</h1></div><div className="heading-actions flex items-center gap-[12px]"><span className="edition text-[9px] text-muted tracking-[1px] max-[600px]:hidden">POSTR / 01</span><button type="button" className="[font-family:inherit] icon-button inline-grid place-items-center [border:0] bg-transparent rounded-full shrink-0 w-[44px] h-[44px] text-blue [&:hover]:bg-[light-dark(#2466c20d,_#86b6f612)]   theme-toggle [&.theme-toggle]:text-ink [&.theme-toggle]:[border:1px_solid_var(--color-line)] [&.theme-toggle]:bg-card" aria-label="Chế độ tối" aria-pressed={theme === 'dark'} title={theme === 'dark' ? 'Chuyển sang chế độ sáng' : 'Chuyển sang chế độ tối'} onClick={toggleTheme}><Icon name={theme === 'dark' ? 'sun' : 'moon'} /></button></div></div></header>
        {children}
      </main>
      <aside className="rightbar [padding:30px_0] max-[880px]:hidden" aria-label="Khám phá cộng đồng">
        <form className="search flex items-center gap-[10px] min-h-[44px] [padding:10px_14px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-card shadow-[3px_3px_0_#efcc62] [&:focus-within]:[outline:2px_solid_var(--color-muted)] [&:focus-within]:[outline-offset:3px] [&_input]:w-full [&_input]:[border:0] [&_input]:[outline:none] [&_input]:bg-transparent [&_input]:text-[12px] [&_svg]:w-[17px] [&_svg]:h-[17px] [&_kbd]:[padding:1px_5px] [&_kbd]:[border:1px_solid_var(--color-line)] [&_kbd]:rounded-[4px] [&_kbd]:text-muted max-[600px]:[&_input]:text-[16px]" role="search" onSubmit={event => { event.preventDefault(); onSearch(); window.location.hash = `search/${encodeURIComponent(search.trim())}` }}><Icon name="search" /><input className="[font-family:inherit]" type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm trên Postr" aria-label="Tìm trên Postr" /><kbd aria-hidden="true">↵</kbd></form>
        <section className="daily-note relative isolate overflow-hidden mt-[24px] p-[22px] [border:1.5px_solid_var(--color-edge)] rounded-[18px] bg-[light-dark(#eedcae,_#393122)] [&_>_small]:text-[8px] [&_>_small]:tracking-[1.3px] [&_h2]:[margin:14px_0_10px] [&_h2]:font-serif [&_h2]:text-[30px] [&_h2]:leading-[1.05] [&_h2]:tracking-[-1px] [&_p]:max-w-[200px] [&_p]:[margin:0_0_17px] [&_p]:text-[11px] [&_p]:leading-[1.65]"><small className="text-xs">CHUYỆN NHỎ HÔM NAY</small><h2 className="[margin:.83em_0] font-bold">Thế giới rộng.<br />Kết nối gần.</h2><p className="[margin:1em_0]">Một ý tưởng hay có thể bắt đầu từ câu chuyện của bạn.</p><button className="[font-family:inherit] text-button inline-flex items-center gap-[6px] p-0 min-h-[30px] [border:0] bg-transparent text-[11px] font-bold [&:hover]:underline" onClick={onCompose}>Kể chuyện của bạn <span aria-hidden="true">↗</span></button><span className="note-star absolute z-[-1] right-[-24px] top-[10px] text-[#cf9a4080] text-[150px] leading-[1]" aria-hidden="true">✳</span></section>
        <section className="side-card mt-[23px] overflow-hidden [border:1.5px_solid_var(--color-edge)] rounded-[18px] bg-card shadow-[4px_4px_0_var(--color-shadow)]"><h2 className="font-bold side-title flex items-center justify-between m-0 [padding:18px_17px] font-serif text-[19px] tracking-[-.5px]">Đang diễn ra <span className="live-dot inline-block shrink-0 w-[6px] h-[6px] rounded-full bg-green" /></h2>{trends.map((trend, index) => <a className="trend flex items-start gap-[10px] [padding:13px_16px] [border-top:1px_solid_var(--color-line)] [&:hover]:bg-[light-dark(#fff5e6,_#2d2821)] [&_>_span:last-child]:ml-auto [&_>_span:last-child]:text-[#a59886] [&_>_span:last-child]:text-[14px] [&_small]:text-muted [&_small]:text-[11px] [&_strong]:block [&_strong]:[margin:4px_0] [&_strong]:text-[14px]" href={`#search/${encodeURIComponent(trend.query)}`} onClick={onSearch} key={trend.title}><span className="trend-rank mt-[2px] text-[#b1a38d] text-[10px]">0{index + 1}</span><div><small className="text-xs">{trend.type}</small><strong>{trend.title}</strong><small className="text-xs">{trend.count}</small></div><span aria-hidden="true">↗</span></a>)}</section>
        <section className="side-card mt-[23px] overflow-hidden [border:1.5px_solid_var(--color-edge)] rounded-[18px] bg-card shadow-[4px_4px_0_var(--color-shadow)]"><h2 className="font-bold side-title flex items-center justify-between m-0 [padding:18px_17px] font-serif text-[19px] tracking-[-.5px]">Có thể bạn biết</h2>{people.slice(0, 3).map(person => <div className="suggestion [&_small]:text-muted [&_small]:text-[11px] grid grid-cols-[33px_minmax(0,_1fr)_auto] items-center gap-[8px] [padding:13px_14px] [border-top:1px_solid_var(--color-line)] [&_.avatar]:w-[33px] [&_.avatar]:h-[33px] [&_.avatar]:text-[16px] [&_strong]:block [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-[12px] [&_.verified]:w-[11px] [&_.verified]:h-[11px] [&_.verified]:text-[8px] max-[1130px]:px-[10px] max-[1130px]:gap-[6px]" key={person.handle}><Avatar person={person} /><div><strong title={person.name}>{person.name} {person.verified && <Verified />}</strong><small className="text-xs">{person.handle}</small></div><button className={`[font-family:inherit] follow inline-flex items-center justify-center min-h-[40px] [padding:7px_11px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-transparent text-[12px] font-bold whitespace-nowrap [&:hover]:bg-[light-dark(#eee7dc,_#393229)] [&.following]:bg-ink [&.following]:text-card [&_svg]:w-[15px] [&_svg]:h-[15px] ${following.includes(person.handle) ? 'following' : ''}`} aria-label={`${following.includes(person.handle) ? 'Bỏ theo dõi' : 'Theo dõi'} ${person.name}`} aria-pressed={following.includes(person.handle)} onClick={() => onFollow(person.handle)}>{following.includes(person.handle) ? <Icon name="check" /> : 'Theo dõi'}</button></div>)}<a className="side-more flex justify-between [border-top:1px_solid_var(--color-line)] [padding:13px_17px] text-blue text-[11px]" href="#search">Khám phá thêm <span aria-hidden="true">↗</span></a></section>
        <p className="side-footer [margin:25px_8px] text-muted text-[11px] leading-[1.9]">Bản trải nghiệm · Dữ liệu mẫu<br />Thao tác được lưu trong bản demo của bạn.<br />© 2026 Postr. Tin tức theo cách của bạn.</p>
      </aside>
    </div>
    <nav className="mobile-nav hidden max-[600px]:fixed max-[600px]:z-[10] max-[600px]:[inset:auto_0_0] max-[600px]:grid max-[600px]:grid-cols-[repeat(6,_1fr)] max-[600px]:[padding:8px_4px_max(8px,_env(safe-area-inset-bottom))] max-[600px]:[border-top:1px_solid_var(--color-edge)] max-[600px]:bg-[light-dark(#f8f3eaf5,_#1b1917f5)] max-[600px]:[backdrop-filter:blur(16px)] max-[600px]:[&_a]:flex max-[600px]:[&_a]:min-w-0 max-[600px]:[&_a]:flex-col max-[600px]:[&_a]:items-center max-[600px]:[&_a]:justify-center max-[600px]:[&_a]:gap-[6px] max-[600px]:[&_a]:min-h-[43px] max-[600px]:[&_a]:text-muted max-[600px]:[&_a_>_span:last-child]:text-[10px] max-[600px]:[&_a_>_span:last-child]:whitespace-nowrap max-[600px]:[&_a.active]:text-[light-dark(#b94221,_#ff936e)] max-[600px]:[&_a.active]:font-bold" aria-label="Điều hướng di động">{navigation.map(item => <a key={item.id} className={active.id === item.id ? 'active' : ''} href={`#${item.id}`} aria-label={item.label} aria-current={active.id === item.id ? 'page' : undefined}><span className="nav-icon relative flex"><Icon name={item.icon} />{item.id === 'bell' && unread && <i className="notification-dot absolute top-0 right-[-1px] h-[7px] w-[7px] bg-accent [border:1px_solid_var(--color-paper)] rounded-full" />}</span><span>{item.label}</span></a>)}</nav>
  </>
}
