import type { ReactNode } from 'react'
import Icon from '@/shared/components/Icon'
import { Avatar } from '@/shared/components/Identity'
import { people, trends } from '@/features/feed/data/feed-content'

export default function ExplorePage({ query, topic, onQuery, onTopic, following, onFollow, children }: {
  query: string; topic: string; onQuery: (value: string) => void; onTopic: (value: string) => void
  following: string[]; onFollow: (handle: string) => void; children: ReactNode
}) {
  return <>
    <section className="explore-header [padding:28px_24px] [&_h2]:[margin:10px_0_24px] [&_h2]:font-serif [&_h2]:text-[33px] [&_h2]:tracking-[-1px] max-[600px]:[padding:24px_18px]"><p className="[margin:1em_0] eyebrow text-[10px] font-bold tracking-[1.6px]">CÓ GÌ MỚI NGOÀI KIA?</p><h2 className="[margin:.83em_0] font-bold">Mở rộng góc nhìn.</h2><label className="search flex items-center gap-[10px] min-h-[44px] [padding:10px_14px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-card shadow-[3px_3px_0_#efcc62] [&:focus-within]:[outline:2px_solid_var(--color-muted)] [&:focus-within]:[outline-offset:3px] [&_input]:w-full [&_input]:[border:0] [&_input]:[outline:none] [&_input]:bg-transparent [&_input]:text-[12px] [&_svg]:w-[17px] [&_svg]:h-[17px] [&_kbd]:[padding:1px_5px] [&_kbd]:[border:1px_solid_var(--color-line)] [&_kbd]:rounded-[4px] [&_kbd]:text-muted max-[600px]:[&_input]:text-[16px]"><Icon name="search" /><input className="[font-family:inherit]" type="search" autoComplete="off" value={query} onChange={event => onQuery(event.target.value)} placeholder="Tìm câu chuyện, tên hoặc hashtag" aria-label="Tìm câu chuyện" /></label></section>
    <div className="topic-filters flex gap-[7px] overflow-x-auto [padding:0_24px_20px] [&_button]:shrink-0 [&_button]:min-h-[40px] [&_button]:[padding:9px_13px] [&_button]:[border:1px_solid_var(--color-line)] [&_button]:rounded-[20px] [&_button]:bg-transparent [&_button]:text-[12px] [&_button.selected]:bg-ink [&_button.selected]:border-edge [&_button.selected]:text-card max-[600px]:px-[18px]" aria-label="Chủ đề">{['Tất cả', 'Đời sống', 'Công nghệ', 'Thiết kế', 'Âm nhạc', 'Thể thao'].map(label => <button key={label} className={topic === label ? 'selected' : ''} aria-pressed={topic === label} onClick={() => onTopic(label)}>{label}</button>)}</div>
    {!query && topic === 'Tất cả' && <>
      <div className="explore-trends grid grid-cols-[1fr_1fr] gap-[13px] [padding:0_24px_24px] [&_button]:min-w-0 [&_button]:[border:1.5px_solid_var(--color-edge)] [&_button]:rounded-[14px] [&_button]:[padding:19px_15px] [&_button]:text-left [&_button]:bg-[light-dark(#efcf8b,_#44351f)] [&_button_+_button]:bg-[light-dark(#dce5d7,_#293b30)] [&_span]:block [&_span]:text-[8px] [&_span]:tracking-[.8px] [&_strong]:block [&_strong]:[margin:21px_0_9px] [&_strong]:font-serif [&_strong]:text-[23px] [&_strong]:[overflow-wrap:anywhere] [&_small]:text-[10px] max-[600px]:px-[18px] max-[600px]:gap-[10px] max-[600px]:[&_strong]:text-[21px]">{trends.slice(0, 2).map((trend, index) => <button className="[font-family:inherit]" key={trend.title} onClick={() => onQuery(trend.query)}><span>0{index + 1} / ĐƯỢC QUAN TÂM</span><strong>{trend.title}</strong><small className="text-xs">{trend.count} ↗</small></button>)}</div>
      <section className="people-section [padding:0_24px_24px] [&_h3]:font-serif [&_h3]:text-[19px] max-[600px]:px-[18px]"><h3 className="[margin:1em_0] font-bold">Những người kể chuyện</h3><div className="people-grid grid grid-cols-[repeat(3,_minmax(0,_1fr))] gap-[10px] max-[600px]:flex max-[600px]:overflow-x-auto max-[600px]:pb-[4px]">{people.slice(0, 3).map(person => <div className="person-card flex flex-col items-center gap-[9px] [padding:17px_8px] [border:1px_solid_var(--color-line)] rounded-[13px] bg-card text-center [&_strong]:text-[13px] [&_small]:text-[11px] [&_small]:text-muted [&_.follow]:mt-auto max-[600px]:[flex:0_0_142px] max-[600px]:[&_.follow]:px-[10px]" key={person.handle}><Avatar person={person} /><strong>{person.name}</strong><small className="text-xs">{person.handle}</small><button className={`[font-family:inherit] follow inline-flex items-center justify-center min-h-[40px] [padding:7px_11px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-transparent text-[12px] font-bold whitespace-nowrap [&:hover]:bg-[light-dark(#eee7dc,_#393229)] [&.following]:bg-ink [&.following]:text-card [&_svg]:w-[15px] [&_svg]:h-[15px] ${following.includes(person.handle) ? 'following' : ''}`} aria-pressed={following.includes(person.handle)} onClick={() => onFollow(person.handle)}>{following.includes(person.handle) ? 'Đang theo dõi' : 'Theo dõi'}</button></div>)}</div></section>
    </>}
    <h3 className="section-label m-0 [padding:15px_24px] [border-block:1px_solid_var(--color-line)] text-[11px] font-bold [overflow-wrap:anywhere]">{query ? `Kết quả cho “${query}”` : 'Câu chuyện nổi bật'}</h3>{children}
  </>
}
