import { useRef, type ReactNode } from 'react'
import Icon from '@/shared/components/Icon'
import { Avatar } from '@/shared/components/Identity'
import type { Profile } from '@/shared/types/post'

export default function ProfilePage({ profile, following, posts, liked, tab, onTab, onSave, children }: {
  profile: Profile; following: number; posts: number; liked: number; tab: string
  onTab: (tab: string) => void; onSave: (profile: Profile) => Promise<void>; children: ReactNode
}) {
  const dialog = useRef<HTMLDialogElement>(null)
  return <>
    <div className="profile-cover flex items-center justify-between h-[165px] overflow-hidden p-[24px] [background:repeating-linear-gradient(-35deg,_transparent_0_25px,_#b4812c12_25px_26px),_light-dark(#eedcae,_#393122)] [&_>_span:first-child]:font-serif [&_>_span:first-child]:text-[28px] [&_>_span:first-child]:italic [&_>_span:first-child]:tracking-[-1px] [&_>_span:last-child]:text-[180px] [&_>_span:last-child]:leading-[1] [&_>_span:last-child]:text-accent [&_>_span:last-child]:[transform:rotate(10deg)] max-[600px]:h-[148px] max-[600px]:p-[18px] max-[600px]:[&_>_span:first-child]:text-[24px] max-[600px]:[&_>_span:last-child]:text-[150px]"><span>Ở đây, mình là mình.</span><span aria-hidden="true">✳</span></div>
    <section className="profile-details [padding:0_24px_24px] [&_h2]:[margin:20px_0_5px] [&_h2]:font-serif [&_h2]:text-[27px] [&_h2]:[overflow-wrap:anywhere] [&_>_.muted]:text-[12px] [&_>_.muted]:m-0 max-[600px]:px-[18px]"><div className="profile-top flex justify-between items-end mt-[-34px] relative [&_.follow]:mb-[5px] [&_.follow]:bg-card"><Avatar person={profile} large /><button className="[font-family:inherit] follow inline-flex items-center justify-center min-h-[40px] [padding:7px_11px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-transparent text-[12px] font-bold whitespace-nowrap [&:hover]:bg-[light-dark(#eee7dc,_#393229)] [&.following]:bg-ink [&.following]:text-card [&_svg]:w-[15px] [&_svg]:h-[15px]" onClick={() => dialog.current?.showModal()}>Chỉnh sửa hồ sơ</button></div><h2 className="[margin:.83em_0] font-bold">{profile.name}</h2><p className="[margin:1em_0] muted text-muted">{profile.handle}</p><p className="[margin:1em_0] profile-bio text-[13px] leading-[1.7] whitespace-pre-wrap [overflow-wrap:anywhere]">{profile.bio}</p><p className="[margin:1em_0] profile-location flex items-center flex-wrap gap-[7px] text-[11px] text-muted [overflow-wrap:anywhere] [&_svg]:w-[14px] [&_svg]:h-[14px] [&_>_span]:ml-[7px]"><Icon name="pin" />{profile.location || 'Chưa cập nhật vị trí'}<span>Tham gia tháng 10, 2026</span></p><div className="profile-stats flex flex-wrap gap-[17px] mt-[22px] text-[11px] text-muted [&_strong]:text-ink"><span><strong>{posts}</strong> bài đăng</span><span><strong>{following}</strong> đang theo dõi</span><span><strong>{liked}</strong> lượt thích đã gửi</span></div></section>
    <div className="tabs grid grid-cols-[1fr_1fr] [border-bottom:1px_solid_var(--color-line)]">{['Bài đăng', 'Đã thích'].map(label => <button key={label} className={`[font-family:inherit] tab relative [padding:18px_8px] min-h-[52px] [border:0] bg-transparent text-muted font-bold text-[13px] [&:hover]:bg-[#e8dfd140] [&.active]:text-ink [&.active::after]:absolute [&.active::after]:bottom-[-1px] [&.active::after]:left-[50%] [&.active::after]:w-[64px] [&.active::after]:h-[3px] [&.active::after]:rounded-[3px] [&.active::after]:bg-accent [&.active::after]:content-[''] [&.active::after]:[transform:translateX(-50%)] max-[600px]:[padding:16px_8px] ${tab === label ? 'active' : ''}`} aria-pressed={tab === label} onClick={() => onTab(label)}>{label}</button>)}</div>
    {children}
    <dialog ref={dialog} className="modal [width:min(550px,_calc(100%_-_28px))] [max-height:calc(100dvh_-_40px)] p-0 overflow-y-auto [border:1.5px_solid_var(--color-edge)] rounded-[20px] bg-card shadow-[8px_8px_0_light-dark(#24221f40,_#00000066)] text-ink [&::backdrop]:bg-[light-dark(#24221f66,_#00000099)] [&::backdrop]:[backdrop-filter:blur(4px)] [&_.composer]:[border:0] max-[600px]:[&_.composer]:[padding:18px_14px]" aria-labelledby="edit-profile-title" onClose={event => { event.currentTarget.querySelector('form')?.reset(); event.currentTarget.querySelector('input')?.setCustomValidity('') }}><div className="modal-heading flex justify-between items-center [padding:17px_22px] [border-bottom:1px_solid_var(--color-line)] [&_h2]:m-0 [&_h2]:font-serif [&_h2]:text-[22px] max-[600px]:p-[16px] max-[600px]:[&_h2]:text-[20px]"><h2 className="[margin:.83em_0] font-bold" id="edit-profile-title">Chỉnh sửa hồ sơ</h2><button className="[font-family:inherit] icon-button inline-grid place-items-center [border:0] bg-transparent rounded-full shrink-0 w-[44px] h-[44px] text-blue [&:hover]:bg-[light-dark(#2466c20d,_#86b6f612)]" aria-label="Đóng chỉnh sửa hồ sơ" onClick={() => dialog.current?.close()}><Icon name="close" /></button></div><form className="profile-form grid gap-[20px] p-[24px] [&_label]:grid [&_label]:gap-[8px] [&_label]:text-[12px] [&_label]:font-bold [&_input]:p-[12px] [&_input]:[border:1px_solid_var(--color-line)] [&_input]:rounded-[9px] [&_input]:bg-paper [&_input]:text-[14px] [&_textarea]:p-[12px] [&_textarea]:[border:1px_solid_var(--color-line)] [&_textarea]:rounded-[9px] [&_textarea]:bg-paper [&_textarea]:text-[14px] [&_.post-button]:w-fit max-[600px]:[&_input]:text-[16px] max-[600px]:[&_textarea]:text-[16px]" key={profile.name + profile.bio + profile.location} onSubmit={async event => {
      event.preventDefault()
      const data = new FormData(event.currentTarget)
      const name = String(data.get('name') ?? '').trim()
      if (!name) { const input = event.currentTarget.elements.namedItem('name') as HTMLInputElement; input.setCustomValidity('Vui lòng nhập tên.'); input.reportValidity(); return }
      try { await onSave({ ...profile, name, initial: Array.from(name)[0].toUpperCase(), bio: String(data.get('bio') ?? '').trim(), location: String(data.get('location') ?? '').trim() }) } catch { return }
      dialog.current?.close()
    }}><label>Tên hiển thị<input className="[font-family:inherit]" name="name" defaultValue={profile.name} required maxLength={50} onInput={event => event.currentTarget.setCustomValidity('')} /></label><label>Giới thiệu<textarea className="w-full min-h-[66px] resize-y border-0 bg-transparent text-[16px] leading-[1.6] placeholder:text-[light-dark(#8b8780,#a99f92)] [font-family:inherit]" name="bio" defaultValue={profile.bio} maxLength={160} /></label><label>Vị trí<input className="[font-family:inherit]" name="location" defaultValue={profile.location} maxLength={80} /></label><button className="[font-family:inherit] post-button inline-flex items-center justify-center ml-auto min-h-[44px] [padding:8px_21px] [border:1.5px_solid_var(--color-edge)] rounded-[100px] bg-accent text-[#24221f] text-[14px] font-bold [&:hover:not(:disabled)]:bg-[#ff906a]">Lưu thay đổi</button></form></dialog>
  </>
}
